### PR TITLE
Added DBus interface and properties.

### PR DESCRIPTION
**Pull request by jdrescher2006**
Added DBus interface for sending data to watch app with callback function. Added DBus properties for IsConnected, Name and Address in order to access them via getProperty from a QML file.

### CODE REVIEW

**Comment by abranson** [comment]
Thanks, do you think that's all you need, or will there be more coming? I think it would be best to hold the release of this until you're ready on your side.

**Comment by jdrescher2006** [comment]
The sport app on the watch has a pause/play button. Is it somehow possible to get the button event into my SFOS app? I thought the send method with callbacks in appsmsgmanager.cpp might do the trick. But unfortunately it does not work at all data is not displayed and callback is undefined. Do you have an idea for this?

**Comment by abranson** [comment]
Usually the watchapps communicate directly with their javascript portions on the phone, but as this is a built-in app then there must be some special signal coming back like with the others. Does the log show anything when you press that button?

**Comment by jdrescher2006** [comment]
I think this looks quite good. With `journalctl -f -l -a` if the button is pressed, I get: `AppMsgManager::mapAppKeys:203 - Unknown appKey value 4 for app with GUID QUuid("{4dab81a6-d2fc-458a-992c-7a1f3b96a970}")`

**Comment by jdrescher2006** [comment]
In appsmsgmanager.cpp I found the lines: `if (info.uuid() != uuid) {qWarning() << "Unknown app GUID while sending message:" << uuid;`. Maybe I can add a signal at that place with the app ID and the button which was pressed. The SFOS app can then register to that signal and wait for events.
I will try that.

**Comment by jdrescher2006** [comment]
I found in appsmsgmanager.cpp the lines `qWarning() << "Unknown appKey value" << it.key() << "for app with GUID" << uuid;`. Maybe I can emit a signal there with the app ID and the key pressed. The signal must be exposed to DBus and an SFOS app can wait for events.

**Pull request merged**
