### PR TITLE
Add DBus interfaces for closing apps and sending data to apps

### PR DESCRIPTION
**Pull request by jdrescher2006**

### CODE REVIEW

**Comment by abranson** [comment]
Looks good, but why four separate commits?

**Comment by jdrescher2006** [comment]
Sorry, I was using the web interface of github to make the commits. So I had to make it for each file individually.

**Comment by abranson** [comment]
Ok, I'll squash them after merge then if you don't have a local checkout.

**Comment by jdrescher2006** [comment]
No problem, feel free. Do you have a plan for the next release?

**Comment by abranson** [comment]
I'll do one over the weekend so you can use this.

**Pull request merged**
